language: java
sudo: false # faster builds

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - parsentev@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always